platform/pal_uefi/src/AArch64/AvsTestInfra.S, platform/pal_uefi/src/pal_pe.c, test_pool/pe/test_c011.c, test_pool/peripherals/test_m001.c, test_pool/peripherals/test_m002.c, test_pool/secure/test_s002.c, val/include/pal_interface.h, val/include/sbsa_avs_pe.h, val/include/val_interface.h, val/src/avs_pe.c, val/src/avs_pe_infra.c, val/src/avs_status.c, val/src/avs_test_infra.c
- API to update ELR will now use UEFI APIs instead of relying on assembly sequence.
- PMUIRQ test will now include init code for few registers so that they are in know state before programming the interrupt
- Cache ops to happen on the struct member accessed, instead of base memory pointer
=> Modified API used for updating ELR and added init code in PMUIRQ test

linux_app/sbsa-acs-app/sbsa_app_main.c, test_pool/pcie/test_p015.c, test_pool/pe/test_c015.c, test_pool/peripherals/test_d003.c, test_pool/power_wakeup/test_u001.c, test_pool/secure/test_s001.c, test_pool/timer_wd/test_t007.c, test_pool/timer_wd/test_t008.c, test_pool/timer_wd/test_w001.c, test_pool/timer_wd/test_w002.c, uefi_app/SbsaAvsMain.c
All watchdogs and system timers would generate interrupt now instead of one.
Removed whitespace, removed check for CNTP_TVAL read-write test.
=> Updated interrupt tests to generate interrupt from all platform timers

val/src/avs_pe_infra.c, val/src/avs_status.c
1. Wait for a fixed time period for the cpu
to turn off, if its already on. Assumption
being that cpu off operation is still pending.
2. Maximum size for error code values increased
to 16 bits.
=> psci: enhance PSCI_CPU_ON error handling

platform/pal_uefi/src/pal_pcie.c, test_pool/peripherals/test_d001.c, test_pool/peripherals/test_d002.c, val/include/pal_interface.h, val/include/sbsa_avs_pcie.h, val/src/avs_pcie.c
Added to support testing emulated PCIe devices in UEFI.
Such systems are not recommended by SBSA, and whether such systems
are fully SBSA compliant will be decided on case to case basis.
=> pcie: fallback on PciIoProtocol to read config

linux_app/sbsa-acs-app/include/sbsa_app.h, test_pool/io_virt/test_i004.c, test_pool/io_virt/test_i005.c, test_pool/pe/test_c015.c, test_pool/power_wakeup/test_u001.c, uefi_app/SbsaAvs.h, val/include/sbsa_avs_pe.h, val/src/AArch64/PeRegSysSupport.S, val/src/AArch64/PeTestSupport.S, val/src/avs_pcie.c, val/src/avs_pe.c, val/src/avs_wakeup.c
Test #15 more robust - first select the cache level before doing a compare of the values.
Test #71 - use wfi instruction instead of PSCI_SUSPEND as wfi is architecturally consistent across platforms.
remove test #58 from the runlist. This test requires a design change.
=> bug fixes for test #15 and test #71

platform/pal_uefi/include/pal_iovirt.h, platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/pal_iovirt.c, val/include/pal_interface.h
IO Remapping Table RevC describes Performance
Monitoring Counter Group nodes. Aligning code
with documentation.
=> pal/uefi: iort: Support PMCG nodes

platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/pal_iovirt.c, platform/pal_uefi/src/pal_pcie.c, test_pool/pcie/test_p003.c, test_pool/peripherals/test_d001.c, test_pool/peripherals/test_d002.c, val/include/pal_interface.h, val/include/sbsa_avs_pcie.h, val/src/avs_pcie.c
Check segment also when searching for device
using BDF value.
Handle pcie config read errors better.
=> pcie: bug fix reading config space

test_pool/pcie/test_p008.c, val/include/pal_interface.h, val/src/avs_pcie.c
Instead of relying on vector address and data values.
=> Bug fix test 58: use msi desc irq number

test_pool/pcie/test_p013.c, test_pool/peripherals/test_d003.c
Use val_print_raw to print test message instead of val_print, since
former uses UART base address taken from SPCR table, and the latter
uses PCD defined UART base address. The GSIV on which ISR is
installed in this test is also from SPCR table. With this change
test message will always trigger the expected interrupt.
Signed-off-by: Prasanth Pulla <prasanth.pulla@arm.com>
=> Test 84 bug fix. Pick UART address from SPCR table.

test_pool/pcie/test_p008.c
BDF value 0 is valid, and should not be discarded.
=> test 58: bug fix: handle BDF return values correctly

platform/pal_uefi/src/pal_timer_wd.c, val/include/val_interface.h, val/src/avs_timer.c
timer tests. Read frame number from GTDT table and use it for register
offset calculations.
=> Fix for issue where Frame number was not being considered for Generic

README.md
It seems the User Guide .pdf got renamed at some point, but the top-level
Readme.md did not get updated to reflect this. Update all links to this file.
=> Fix User Guide links in Readme.md

val/include/sbsa_avs_pe.h, val/src/avs_pe_infra.c
Added the fix in avs_pe_infra.c - val_pe_get_mpid.
Signed-off-by: Rajat Goyal <rajat.goyal@arm.com>
=> Fix for wrong Affinity bits in val_pe_get_mpid

test_pool/io_virt/test_i001.c, test_pool/io_virt/test_i004.c, test_pool/io_virt/test_i005.c, test_pool/pcie/test_p030.c, test_pool/pcie/test_p031.c, test_pool/pcie/test_p032.c, test_pool/pcie/test_p033.c, test_pool/pcie/test_p034.c, test_pool/pcie/test_p035.c, test_pool/pcie/test_p036.c, test_pool/pcie/test_p037.c, test_pool/pcie/test_p038.c, test_pool/pcie/test_p039.c, test_pool/pcie/test_p040.c, test_pool/pcie/test_p041.c, test_pool/pcie/test_p042.c, test_pool/pcie/test_p043.c, test_pool/pcie/test_p044.c, test_pool/pcie/test_p045.c, val/include/pal_interface.h, val/src/avs_pcie.c
PCIe : Test Updates
- Added Skip logic in test to skip the test when test is not being done for any of the endpoint.
- Comparison of unsigned expression < 0 is always false.
Io-Virt : Test Fixes
- Io-Virt tests updates to handle false pass/fail
=> PCIe, Io-Virt Test Fixes and Enhancements

platform/pal_baremetal/FVP/include/platform_override_fvp.h, platform/pal_baremetal/include/pal_pcie_enum.h, platform/pal_baremetal/src/pal_pcie_enumeration.c, platform/pal_uefi/src/pal_misc.c, test_pool/pcie/test_p003.c, test_pool/pcie/test_p005.c, test_pool/pcie/test_p012.c, test_pool/pcie/test_p046.c, uefi_app/SbsaAvs.inf, uefi_app/SbsaAvsNist.inf, val/include/pal_interface.h, val/include/sbsa_avs_common.h, val/include/sbsa_avs_pcie.h, val/include/sbsa_avs_pcie_spec.h, val/src/avs_pcie.c, val/src/avs_test_infra.c
- Extended coverage for test_p003 and access the entire BDF space and access register in 256B
and greater than 256B
- Added test_p046
=> PCIe : Updates & Enhancements

README.md, docs/Arm_SBSA_NIST_User_Guide.md, platform/pal_uefi/SbsaPalLib.inf, platform/pal_uefi/SbsaPalNistLib.inf, platform/pal_uefi/src/pal_acpi.c, test_pool/nist_sts/SbsaNistLib.inf, tools/scripts/avsbuild.sh, tools/scripts/avssetup.sh, uefi_app/SbsaAvs.inf, uefi_app/SbsaAvsNist.inf
SBSA changes required to build ACS on the latest EDK II
firmware tagged edk2-stable202008.
=> EDKII: Migration to edk2-stable202008

test_pool/pcie/test_p019.c, test_pool/pcie/test_p057.c, val/include/pal_interface.h, val/src/avs_pcie.c
- The return value was changed for newly developed PCIe
test 57 but was not changed in the existing test 19.
Changing back to original value to be in consistent with
other function.
- Added logic in test_p019 to check for rest of the PCIe
devices eventhough some fails.
- Removed C99 standard code ;;
Change-Id: I5c9c39e07c6da40ea8b411e034ee464c4ea9a119
=> PCIe: Changing the return value for val_pcie_multifunction_support

platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/pal_gic.c, platform/pal_uefi/src_gic_its/sbsa_gic_its.c, platform/pal_uefi/src_gic_its/sbsa_gic_its.h, test_pool/peripherals/test_m001.c, uefi_app/SbsaAvsMain.c, val/include/pal_interface.h
Include the following updates.
- GIC
- Fixed GICR base address calculation based on the available configuration. 
- Added support for reading GICR Base from GICC structure & GICR structure based on the configuration.
- Added extra checks for failure case.
- Peripheral
- Removed IRQ/FIQ esr from the test.
=> GIC : Fixed GICR Base Calculation, Peripheral : Fixed test_m001

test_pool/pcie/test_p048.c, test_pool/pcie/test_p049.c
The code to check if read value is valid or not need to compare
with the old value, not just based on all F's
=> PCIe: P and NP memory access check updates for test 448 and 449

test_pool/pcie/test_p034.c, val/include/sbsa_avs_pcie_spec.h
- test_c034 extracts header type register for a bdf and
ignores to discard the multifunction support bit. The
test has been modified to use existing val_pcie_function_header_type()
function.
=> PCIe: Using val_pcie_function_header_type() to extract header type

test_pool/pcie/test_p004.c, test_pool/pe/test_c022.c, val/include/sbsa_avs_pcie_spec.h
test_c022 : Updated Pointer Signing test
- All PEs must implement pointer signing indicated
by ID_AA64ISAR1_EL1.APA having a non-zero value.
PCIe: Test only if the BAR is memory address space mapped
- test_p004 should perform the tests only if the BAR is
memory address space mapped and not IO address space mapped.
This is determined by reading bit 0 of BAR.
=> Bug Fix for test_c022, test_p004

test_pool/exerciser/test_e004.c
- Exerciser test_e004 get the count of peripheral device
present in the system which is not required. Hence removing
that code.
Change-Id: I93ab2fe9a3ed071e1a2079a9d84e243af0943d45
=> Exerciser: Removing unused code requiring peripheral device

test_pool/power_wakeup/test_u001.c, test_pool/timer_wd/test_w002.c, val/src/avs_wd.c
Added counter frequency multiplier to timeout value in
val_wd_set_ws0(),since without this change, the timeout
value written by the testcase into watchdog device was
too small causing system reset even before watchdog refresh.
Change-Id: If7a979855a47d6a8ad680b5a87edf92d7d88fed2
=> WDOG: Added counter frequency multiplier to wd timeout

test_pool/peripherals/test_d003.c
When built with gcc 10.2-2020.11, the UART read following the write
was incorrectly being optimized and not hitting the hypervisor.
Fix this by adding 'volatile' to those acceses.
Signed-off-by: Rebecca Cran <rebecca@nuviainc.com>
=> Fix test 603: mark UART register pointers volatile

platform/pal_uefi/src/pal_gic.c
clang complains about enum type mismatches:
pal_uefi/src/pal_gic.c:224:20: error: implicit conversion from enumeration type
'INTR_TRIGGER_INFO_TYPE_e' to different enumeration type 'EFI_HARDWARE_INTERRUPT2_TRIGGER_TYPE'
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> pal_uefi: Fix enum conversion

test_pool/Makefile
test_pool/pcie/test_p004.c was deleted in commit
7775a1729811ec695253cc4ae8d0350eeecb0671 - also remove it from
test_pool/Makefile.
Signed-off-by: Rebecca Cran <rebecca@nuviainc.com>
=> Remove pcie/test_p004.o from test_pool/Makefile

val/Makefile
Removed unused file avs_gic_support.c from SBSA linux test
compilation.
=> Makefile: Removing unused file from compilation

test_pool/pcie/test_p008.c, test_pool/pcie/test_p009.c, test_pool/pcie/test_p012.c, test_pool/pcie/test_p014.c
- Replaced kzalloc and free linux function calls with
val_memory_alloc and val_memory_free functions.
- Remove unused variable dma_addr in test_p014.
=> PCIe: Removed linux API reference from PCIe test

test_pool/timer_wd/test_t007.c
* Write whole 64 bit first
* Then read & compare
* Fix: https://github.com/ARM-software/sbsa-acs/issues/167
=> Updated CNTP_CVAL RW sequence

platform/pal_baremetal/FVP/src/platform_cfg_fvp.c, platform/pal_baremetal/include/pal_common_support.h, platform/pal_baremetal/src/pal_pcie.c, test_pool/exerciser/test_e006.c, test_pool/exerciser/test_e008.c, test_pool/exerciser/test_e011.c, test_pool/pcie/test_p005.c, test_pool/pcie/test_p008.c, test_pool/pcie/test_p009.c, test_pool/pcie/test_p046.c, val/include/sbsa_avs_pcie.h, val/include/sbsa_avs_pcie_spec.h, val/include/val_interface.h, val/src/avs_pcie.c
PCIe: MSI: Test to skip if no msi vectors found
- Initially, the test was passing if no MSI vectors were found.
It has been modified to skip if no MSI vectors are found.
PCIe: Test 405 runs for all PCIe devices
- Modified to use PCIe table instead peripheral table to get
the PCIe device BDF.
PCIe: Using Bus number register to perform checks
- Bus number register is the only register in the list of
mandatory registers that have continuous 24 bit read/write
fields. No 32 bit read/write register is available.
- Removed 32 bit write check.
PCIe: Skip test 811 if ATS is not supported
- Exerciser Test-811 is passing instead of skipping when
the exerciser functions don't support ATS.
Exerciser: Updated legacy interrupt test 806
- Obtain the interrupt numbers from platform cfg for
bare-metal for …
=> PCIe test enhancements and bug fixes

test_pool/peripherals/test_d003.c
Fix for issue  : https://github.com/ARM-software/sbsa-acs/issues/149
Fix: write fixed space char to uart data reg instead of default value
and removed a space from test desc.
=> Fix for test 603

platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/pal_peripherals.c, test_pool/gic/test_g003.c, test_pool/pe/test_c014.c, uefi_app/SbsaAvs.h, uefi_app/SbsaAvsMain.c, val/include/sbsa_avs_cfg.h, val/src/avs_peripherals.c
Added return after the failure case in GIC
Fix for PE breakpoint check similar to BSA
Fix for limiting memory info table entry in pal_peripheral.c
Increased Skip test num from 3 to 9
=> Fix for Gic, PE Breakpoints, increased Mem Table size

val/include/sbsa_avs_cfg.h
Fixed limit for skipping test in linux to 3
=> val : Fixed limit for skipping test in linux to 3

test_pool/timer_wd/test_w001.c, test_pool/timer_wd/test_w002.c
" -skip 301,302" doesn't work. It shows "USER OVERRIDE  - Skip Test"  message, but still runs the tests. 
301 : Check NS Watchdog Accessibility
USER OVERRIDE  - Skip Test        : Result:  PASS
302 : Check Watchdog WS0 interrupt
USER OVERRIDE  - Skip Test        : Result:  PASS
=> Tests 301 and 302 : Fix -skip not working issue.

platform/pal_baremetal/src/pal_misc.c, platform/pal_uefi/src/pal_misc.c, platform/pal_uefi/src/pal_timer_wd.c, test_pool/power_wakeup/test_u001.c, test_pool/timer_wd/test_t008.c, test_pool/timer_wd/test_w001.c, test_pool/timer_wd/test_w002.c, test_pool/timer_wd/test_w003.c, val/src/avs_wd.c
WD: Watchdog ctrl base is incorrectly accessed as 32 bit which was leading to crash in some systems.
Status Field: Due to UART print delay after enabling timeout in wakeup test the status field was not correctly updated in some systems.
=> Fix for WD test and wakeup tests status field incorrect update

val/src/avs_wd.c
Test skips itself if run below level 5:
*** Starting Watchdog tests ***
301 : Check NS Watchdog Accessibility   : Result:  PASS
302 : Check Watchdog WS0 interrupt      : Result:  PASS
303 : Check NS Watchdog Revision        : Result:  -SKIPPED- 1
So why run it at all?
=> Do not run test 303 below SBSA level 5

uefi_app/SbsaAvsMain.c
Current code has them mis-aligned:
```
***  Starting PE tests ***
***  Starting GIC tests ***
*** Starting Timer tests ***
*** Starting Watchdog tests ***
*** Starting PCIe tests ***
*** Starting Power and Wakeup semantic tests ***
*** Starting Peripheral tests ***
*** Starting IO Virtualization tests ***
*** Starting PCIe Exerciser tests ***
```
=> Align 'Starting xyz tests' messages

test_pool/timer_wd/test_w001.c
Was:
```
301 : Check NS Watchdog Accessibility
Found 1 watchdogs in ACPI table : Result:  PASS
302 : Check Watchdog WS0 interrupt
WS0 Interrupt id  48
Setting Trigger type as 1
Received WS0 interrupt            : Result:  PASS
```
Is:
```
301 : Check NS Watchdog Accessibility
Found 1 watchdogs in ACPI table   : Result:  PASS
302 : Check Watchdog WS0 interrupt
WS0 Interrupt id  48
Setting Trigger type as 1
Received WS0 interrupt            : Result:  PASS
```
=> test 301: align output in Debug mode

val/src/avs_peripherals.c
Was:
SMMU_INFO: Number of SMMU CTRL       :    1
val_smmu_init: only SMMUv3.x supported, skipping smmu 0
smmu_set_state: smmu unsupported      Peripheral: Num of USB controllers
:    2
Peripheral: Num of SATA controllers  :    4
Is:
SMMU_INFO: Number of SMMU CTRL       :    1
val_smmu_init: only SMMUv3.x supported, skipping smmu 0
smmu_set_state: smmu unsupported
Peripheral: Num of USB controllers   :    2
Peripheral: Num of SATA controllers  :    4
Peripheral: Num of UART controllers  :    1
=> improve printing table on SMMU v2 systems

uefi_app/SbsaAvsMain.c, val/src/avs_exerciser.c
So no need to inform about them on lower levels.
=> PCIe Exerciser tests are SBSA level 4+

test_pool/peripherals/test_d003.c
It was done in past and looks like someone reverted it by mistake.
=> test 604: decapitalize Generic again

test_pool/io_virt/test_i004.c
Was:
```
703 : SMMU Compatibility Check          : Result:  PASS
704 : If PCIe, Check Stall model
Not valid for SMMU v2           : Result:  -SKIPPED- 1
705 : SMMUv2 unique intr per ctxt bank  : Result:  PASS
```
=> test 704: align output on SMMU v2

val/src/avs_pcie.c
Was:
```
PCIE_INFO: Number of ECAM regions    :    2
PCIe Hierarchy fail: RP of bdf 0x2010000 not foundCreate Bdf table failed
.
Invalid IORT node type
SMMU_INFO: Number of SMMU CTRL       :    1
```
Now:
```
PCIE_INFO: Number of ECAM regions    :    2
PCIe Hierarchy fail: RP of bdf 0x2010000 not found
Create Bdf table failed.
Invalid IORT node type
SMMU_INFO: Number of SMMU CTRL       :    1
```
=> fix PCIe errors output

test_pool/timer_wd/test_w003.c
- corrected failure error message
- test was made mandatory for level 6 and above.
=> WD test 303 changes

val/src/avs_pcie.c
It could be helpful to see which values are present and which are expected in PCIe tests.
```
424 : Check Device capabilites reg rules
BDF 0x100 : ETFS value mismatch: 0x0 instead of 0x1
BDF 0x300 : ETFS value mismatch: 0x0 instead of 0x1
BDF 0x100 : ETFS value mismatch: 0x0 instead of 0x1
BDF 0x300 : ETFS value mismatch: 0x0 instead of 0x1
Failed on PE -    0 for Level=  3 : Result:  --FAIL-- 4 
425 : Check Device Control register rule
BDF 0x100 : WARNING PFE attribute mismatch: 0x200 instead of 0x0
BDF 0x100 : WARNING APPE attribute mismatch: 0x400 instead of 0x0
BDF 0x300 : WARNING PFE attribute mismatch: 0x200 instead of 0x0
BDF 0x300 : WARNING APPE attribute mismatch: 0x400 instead of 0x0
BDF 0x100 : WARNING PFE attribute mismatch: 0x200 instead of 0x0
BDF 0x100 : WARNING APPE …
```
=> Show expected/present values for PCIe tests

test_pool/power_wakeup/test_u001.c, val/include/sbsa_avs_pe.h, val/src/AArch64/PeTestSupport.S, val/sys_arch_src/smmu_v3/smmu_v3.c, val/sys_arch_src/smmu_v3/smmu_v3.h
- SMMU init code updated with timeout and memory barrier.
- Test 501 updated to treat PE wakeup from any interrupt as success
=> SMMU hang issue fix and WD test 504 updates

val/sys_arch_src/smmu_v3/smmu_v3.c
Fix For Linux Build Failure
- Fix for Linux build fail due to memory barrier api
https://github.com/ARM-software/arm-enterprise-acs/issues/123
Signed-off-by: Rajat Goyal <rajat.goyal@arm.com>
=> Fix For Linux Build Failure

test_pool/peripherals/test_d003.c, val/include/val_interface.h, val/src/avs_test_infra.c
Changes
* Handle exceptions raised if any during UART register access
* If no UART found in system treat it as FAIL case
* Use uart base of respective UART for interrupt generation
=> Peripheral test 3 updated for multiple uarts

platform/pal_baremetal/include/pal_common_support.h, platform/pal_baremetal/src/pal_pcie_enumeration.c, test_pool/pcie/test_p005.c
- Function is modified to avoid over writing of bar value
and enable better readability
=> PCIe: pal_pcie_get_base() function bug fix

test_pool/timer_wd/test_t007.c
* Added CNTFRQ/CNTVCT RO check
* Removed CounterID check as this is a IMPDEF field
-> https://github.com/ARM-software/sbsa-acs/commit/48563e28c3a0f22e45eb1023649310b17744bddb
*  write whole 64 bit first and then read for AArch64 regs
-> https://github.com/ARM-software/sbsa-acs/commit/e8d6a68b728af4d6fe83773b46a9c679d96cb161
=> Bug fixes on timer test-7

test_pool/pcie/test_p030.c, test_pool/pcie/test_p043.c, val/include/sbsa_avs_pcie_spec.h, val/src/avs_pcie.c
- Test p030.c
When MSE is disabled, Root is required to treat this request as
a UR completion. PCIe forbids root ports from logging UR in
device status for outbound requests.
- Test p043.c
The secondary and primary bus values of RP will not be 0
as it will be set during enumeration. Whether a device is
present below a RP can be verified by checking the
Data Link Layer Link Active of RP
- Adding seg_num check for RP derivation.
Co-Authored-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
Co-authored-by: Chetan Rathore <chetan.rathore@arm.com>
=> PCIe: Fix for issues #232 and #238

uefi_app/SbsaAvs.h
Size of the GIC INFO table is increased to accommodate up to 832 gic entries of MADT table.
=> Github #235 GIC test assert due to insufficient size

test_pool/power_wakeup/test_u001.c, test_pool/timer_wd/test_t001.c, test_pool/timer_wd/test_w002.c, uefi_app/SbsaAvsMain.c, val/src/avs_wd.c
* Moved timeout in multiples of system counter frequency for power and wakeup tests
* In case the default value is not sufficient in some system, added timeout variable to increased timeout value in multiples of system counter.
=> Github #242 Moved timeout in multiples of system counter frequency

baremetal_app/SbsaAvsMain.c, platform/pal_baremetal/FVP/include/platform_override_fvp.h, platform/pal_baremetal/src/pal_misc.c, platform/pal_baremetal/src/pal_pcie.c, platform/pal_baremetal/src/pal_pcie_enumeration.c, platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/include/platform_override.h, platform/pal_uefi/src/pal_misc.c, platform/pal_uefi/src/pal_pcie.c, test_pool/exerciser/test_e006.c, test_pool/exerciser/test_e008.c, test_pool/exerciser/test_e011.c, test_pool/pcie/test_p048.c, test_pool/pcie/test_p049.c, uefi_app/SbsaAvsMain.c, val/include/pal_interface.h, val/include/sbsa_avs_exerciser.h, val/include/sbsa_avs_pcie.h, val/include/val_interface.h, val/src/avs_memory.c, val/src/avs_pcie.c
- pal_mem_alloc: Use memalign when aligned address is required
- Pass runtime params for PCIe supported features
pal_pcie_p2p_support() and pal_pcie_is_cache_present()
- Fix for enumeration of Prefetchable memory range
- Provide custom offset input for test p048.c and p049.c
- Received Master Abort bit to be set in the Exerciser for
Completions with a Completion Status of Unsupported Request
=> PCIe: Fixes and updates

val/src/avs_exerciser.c, val/src/avs_iovirt.c, val/sys_arch_src/smmu_v3/smmu_v3.c
SBSA acs smmu init code is required for pcie exerciser test only. 
Fix for #233
=> Initializing SMMU only if pcie exerciser devices present in system 

test_pool/pcie/test_p008.c
Warn if BDF is 0x0, instead of fail
=> PCIe: Test fix to skip BDF

val/include/sbsa_avs_pcie_spec.h, val/src/avs_gic_support.c, val/src/avs_pgt.c, val/sys_arch_src/gic/its/sbsa_gic_its.c, val/sys_arch_src/gic/its/sbsa_gic_its.h, val/sys_arch_src/gic/v3/gic_v3.c, val/sys_arch_src/smmu_v3/smmu_v3.c
- SMMU: enable 52bits address range
- Fix the RD Base shift
- Shift Return the Processor Number
=> SMMU and ITS

test_pool/pcie/test_p030.c, val/src/avs_pcie.c
In some system, test 430 runs into endless prints due to invalid values of bdf. The root cause was timing of serror exception generaton w.r.t test flow.
Delay is added in the test after exception generation point for exception generation.
=> #257: Delay added for handling exception(serror) timing

test_pool/timer_wd/test_w003.c, uefi_app/SbsaAvsMain.c, val/include/sbsa_avs_cfg.h, val/include/val_interface.h, val/src/avs_exerciser.c, val/src/avs_gic.c, val/src/avs_nist.c, val/src/avs_pcie.c, val/src/avs_pe.c, val/src/avs_peripherals.c, val/src/avs_smmu.c, val/src/avs_test_infra.c, val/src/avs_timer.c, val/src/avs_wakeup.c, val/src/avs_wd.c
This pull requests proposes a new set of parameters to the testing suite that allows the user to select specific test modules instead of being forced to run all of them. Having this feature greatly aids automated testing solutions and allows for more rapid debugging and testing of specific SBSA tests.
=> Add ability to select individual tests or skip test modules

test_pool/pcie/test_p048.c, test_pool/pcie/test_p049.c, val/include/sbsa_avs_pcie_spec.h
- Skip check of "Accessing out of memory limit range
should return 0xFFFFFFFF" for RP's with an Ethernet
or Display controller under them
=> PCIe: Updates to test p048 and p049

test_pool/pe/test_c015.c
This PR fixes an SBSA crash for virtualized environments that do not natively support PMUv3.
=> Check for PMUv3 support before reading registers

platform/pal_uefi/src/pal_pe.c
ACS PE tests do not execute properly on aarch64 systems due to secondary stack misalignment. The arm handbook mentions that aarch64 requires a 16 byte alignment.
This PR includes modifications that allow for aarch64 compatible alignment as well as storing the original pointer given to us by AllocatePool so we can still free the memory if the need ever comes up.
=> Adjusted PalAllocateSecondaryStack to provide aarch64 required 16-byte alignment

platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/AArch64/ArmSmc.S, platform/pal_uefi/src/pal_acpi.c, platform/pal_uefi/src/pal_pe.c, val/include/pal_interface.h, val/include/sbsa_std_smc.h, val/src/avs_pe_infra.c, val/src/avs_wakeup.c
This pull request fixes issue #263.
Summary of changes:
- A global variable `gPsciConduit` is created to store the conduit used for PSCI calls. This value is initialized during the call to `val_pe_create_info_table`.
- A function `pal_get_fadt_ptr` is added, which performs the lookup of the FADT table.
- A function `pal_psci_get_conduit` is added, which checks the FADT table and returns the PSCI conduit, or `-1` if PSCI is not implemented.
- `ArmCallSmc` and `pal_pe_call_smc` take an additional conduit argument, whose value determines whether `ArmCallSmc` will execute an `hvc` instruction or an `smc` instruction. In case of an invalid conduit, `ArmCallSmc` returns `-3`, which is `INVALID_PARAMETER` in SMCCC.
The reason why conduit is passed as a parameter instead of being retrieved from …
=> Determine service call conduit from the FADT table

test_pool/pcie/test_p007.c, test_pool/pcie/test_p041.c
* Test 41 updated to reflect 
RE_INT_1 If the RCiEP supports interrupt generation, the RCiEP must support MSI or MSI-X interrupt generation.
* Debug print also added in pcie test 7 and 41
=> PCIe test 41 updated to fail when RCiEP supports only legacy interrupt and no MSI/MSI-X interrupt.

test_pool/io_virt/test_i010.c
- Update the Granular check for Architecture version greater than v8.5 which would support FEAT_LPA2.
=> Test enhancement: iovirt test_i010.c

test_pool/pcie/test_p048.c, test_pool/pcie/test_p049.c, val/include/sbsa_avs_pcie_spec.h, val/src/avs_pcie.c
- If Device is iEP_RP, set RP value to same BDF
- Skip check of "Accessing out of memory limit range"
with mass storage controller
=> PCIe: Update tests

test_pool/peripherals/test_d003.c
* The change fixes the build issue observed in GCC 12.XX.
* Looks like GCC is confusing label to a local variable and hence triggers dangling-pointer error when a label addres is assigned to a pointer.
* Changed branch_to_test from void * pointer to uint64_t datatype since we just need the retrun address of the label while updating the ELR. This should suppress the dangling-pinter warning thrown by GCC 12.XX
Signed-off-by: Shyamanth RH <shyamanth.rh@arm.com>
=> Fix for issue #245

val/include/val_interface.h, val/src/avs_gic.c
These are flagged by gcc13
avs_gic.c:241:1: error: conflicting types for 'val_gic_get_info' due to enum/integer mismatch; have 'uint32_t(uint32_t)' {aka 'unsigned int(unsigned int)'} [-Werror=enum-int-mismatch]
|   241 | val_gic_get_info(uint32_t type)
|       | ^~~~~~~~~~~~~~~~
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Fix function protype mismatches

test_pool/watchdog/operating_system/test_w001.c
- Changed SBSA watchdog test 301 to fail if no non-secure watchdog timer is found.
=> For SBSA complaince, NS watchdog is mandatory

platform/pal_uefi/src/pal_peripherals.c, test_pool/memory_map/operating_system/test_m001.c, val/src/avs_peripherals.c
Bug Fix for #293 
- Updated the PAL Peripheral table to check for all BAR registers
- Added Debug prints for test m001
- Check for all Peripheral devices even if it fails on one device in test m001.c
=> Fix for Issue #293: Update to memory_map test test_m001.c

uefi_app/SbsaAvsMain.c
Issue #299 : S_L3SM_01 is not tested on level 3
- Test was being skipped because there was a level check in the code, in the file "uefi_app/SbsaAvsMain.c". To resolve this issue, the check was removed and now it is based on the conditions in "avs_smmu.c" instead.
=> Issue #299 : S_L3SM_01 is not tested on level 3

platform/pal_uefi/src/pal_pe.c
Fix for SBSA-ACS similiar to https://github.com/ARM-software/bsa-acs/issues/132 
* Check MADT (GICC CPU interface flags) enabled and online capable bit
* if either of those bits are set, then only add pe
* if both bits are clear, pe is unusable
=> Only add usable PE in pe_info_table

test_pool/pe/operating_system/test_c015.c
Fix for #302 
SBSA rule requires atleast two PMG
Value of PMG_MAX means largest value of PMG that the implementation can generate.
Value 1 will means PMG 0 and 1 present
=> Correct the minimum PMG present check condition

platform/pal_baremetal/FVP/RDN2/include/platform_override_struct.h, platform/pal_baremetal/FVP/RDN2/src/platform_cfg_fvp.c, platform/pal_baremetal/include/pal_common_support.h, platform/pal_baremetal/src/pal_iovirt.c, platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/pal_iovirt.c, test_pool/smmu/operating_system/test_i014.c, test_pool/smmu/operating_system/test_i016.c, val/include/pal_interface.h, val/include/val_interface.h, val/src/avs_iovirt.c
Replace ETR CID with HID
- CID will only be a subset of ETR devices but HID will
cover every ETR and acpi_get_devices only capable to match
the HID not CID.
- HID for ETR devices included in ARMHC97C. Refer
https://developer.arm.com/documentation/den0067/a/
SBSA 714 test and PMCG parsing bug fix
- The PMCG info node reference is offset to the RC,SMMU etc node from start of
ACPI IORT table. instead offset of same PMCG node was getting stored.
- For test 714 we need to check whether PMCG is associated with a SMMU
to do that we can see if node_reference + start address of IORT ACPI
table points to a SMMU during parsing and store smmu_base if found
for testing purpose.
Signed-off-by: Amrathesh [amrathesh@arm.com](mailto:amrathesh@arm.com)
=> Bug fixes in PMCG parsing code and ETR device HID

test_pool/exerciser/operating_system/test_e009.c, test_pool/mpam/operating_system/test_mpam003.c, test_pool/pcie/operating_system/test_p003.c, test_pool/pcie/operating_system/test_p007.c, test_pool/pcie/operating_system/test_p014.c, test_pool/pcie/operating_system/test_p034.c, test_pool/pcie/operating_system/test_p035.c, test_pool/pcie/operating_system/test_p039.c, test_pool/pcie/operating_system/test_p048.c, test_pool/pcie/operating_system/test_p049.c, test_pool/pcie/operating_system/test_p052.c, test_pool/pcie/operating_system/test_p056.c, test_pool/pcie/operating_system/test_p060.c, test_pool/pe/operating_system/test_c001.c, test_pool/pmu/operating_system/test_pmu004.c, test_pool/pmu/operating_system/test_pmu007.c, test_pool/pmu/operating_system/test_pmu008.c, test_pool/pmu/operating_system/test_pmu009.c, test_pool/ras/operating_system/test_ras006.c, test_pool/smmu/operating_system/test_i001.c, test_pool/smmu/operating_system/test_i002.c, test_pool/smmu/operating_system/test_i014.c, test_pool/smmu/operating_system/test_i016.c
- "must" carries a stronger sense of obligation or necessity than "should" hence using it for prints conveying non-compilance to mandatory rules.
Fixes #309
=> use of verb "must" in place "should" to express requirements

baremetal_app/SbsaAvsMain.c, uefi_app/SbsaAvsMain.c, val/src/avs_pcie.c, val/src/avs_wd.c
Fix for #307 
- Changed condition to execute watchdog tests for level greater than 5
- Removed conditions checking for level greater than 2
- Removed unreachable code form val/src/avs_pcie.c
=> Synchronize level checks

val/src/avs_mpam.c
Fixes a compile error with a misplaced bracket.
Fixes: 4b36750 ("SBSA 7.1 Changes")
=> val: src: avs_mpam: Fix compile error

val/src/avs_mpam.c
This is a 64-bit register. The compiler caught an invalid bit shift when trying to access HAS_RIS (bit 32).
=> val: src: avs_mpam: Fix read of MPAMF_IDR

uefi_app/SbsaAvs.h
Increase IORT Table Size
- Increased the IORT Info table size to accomodate 600 typical IORT nodes. 
- Issue https://github.com/ARM-software/bsa-acs/issues/134
=> Increase IORT Table Size

val/src/avs_pcie.c
- Added TARGET_LINUX guard to not run PCIe tests 61 and 62 on Linux SBSA.
=> Added TARGET_LINUX guard to PCIe tests 61 and 62

test_pool/smmu/operating_system/test_i001.c, test_pool/smmu/operating_system/test_i002.c, uefi_app/SbsaAvsMain.c, val/src/avs_smmu.c
- test 302 covers S_L5SM_01, S_L5SM_02 directly. S_L3SM_01 is removed since it is waived off for its IMPDEF implications.
- since test 302 runs for level >=5, redundant level checks and dead code is removed.
- corrected RULE to test mapping.
Resolves: #308
=> SMMU test 301 & 302 test reorder and updates

baremetal_app/SbsaAvsMain.c, platform/pal_baremetal/FVP/RDN2/include/platform_override_fvp.h, platform/pal_baremetal/FVP/RDN2/src/platform_cfg_fvp.c, uefi_app/SbsaAvsMain.c, val/include/sbsa_avs_cfg.h, val/include/sbsa_avs_common.h, val/src/avs_exerciser.c, val/src/avs_gic.c, val/src/avs_memory.c, val/src/avs_mpam.c, val/src/avs_nist.c, val/src/avs_pcie.c, val/src/avs_pe.c, val/src/avs_peripherals.c, val/src/avs_pmu.c, val/src/avs_ras.c, val/src/avs_smmu.c, val/src/avs_test_infra.c, val/src/avs_timer.c, val/src/avs_wakeup.c, val/src/avs_wd.c
- Resolves: #328 
- Removed the limitation on number of tests and modules to be run using -t and -m options in UEFI and Baremetal.
=> Removed limitation on -t and -m options

test_pool/smmu/operating_system/test_i003.c, test_pool/smmu/operating_system/test_i004.c
- test 303 & 304 were falsely passing when Secure EL2 was not implemented.
- added a check for secure EL2, so that test can be skipped if it is not implemented.
=> Test 303 & 304 test enchancements

test_pool/smmu/operating_system/test_i005.c, test_pool/smmu/operating_system/test_i006.c, test_pool/smmu/operating_system/test_i008.c, test_pool/smmu/operating_system/test_i011.c, test_pool/smmu/operating_system/test_i012.c, test_pool/smmu/operating_system/test_i013.c, test_pool/smmu/operating_system/test_i015.c, val/src/avs_smmu.c
- tests are being reordered based SBSA spec.
- SMMU support for MPAM test moved from L6 to L5.
- PCIe presence checks removed from few SMMU tests as they are redundant.
=> SMMU tests reordering and enhancements

test_pool/pe/operating_system/test_c030.c
Fix for #329 
-  Renaming PE test 30 test description to be more precise
=> Rename PE test 30 description

val/include/sbsa_avs_pcie_spec.h, val/src/avs_pcie.c
- Fix for issue https://github.com/ARM-software/bsa-acs/issues/150
- Added changes to print additional information on the number of Upstream ports of a switch, Downstream ports of a switch, PCIe to PCI/PCI-X Bridge and PCIe to PCI/PCI-X to PCIe Bridge to match the total BDF's identified
=> Added additional prints to print info of all cards in PCI info block

test_pool/pcie/operating_system/test_p003.c
- Modified print while skipping legacy PCI devices in test_p003
- Resolves: #339
=> Modified print on skipping legacy PCI cards

platform/pal_baremetal/FVP/src/pal_bm_misc.c, test_pool/pcie/operating_system/test_p017.c, test_pool/pcie/operating_system/test_p030.c, test_pool/pcie/operating_system/test_p035.c, test_pool/pcie/operating_system/test_p036.c, test_pool/pcie/operating_system/test_p040.c, test_pool/pcie/operating_system/test_p044.c, test_pool/pcie/operating_system/test_p045.c, test_pool/pcie/operating_system/test_p046.c, test_pool/pcie/operating_system/test_p047.c, test_pool/pcie/operating_system/test_p048.c, test_pool/pcie/operating_system/test_p049.c
- Added an else condition in test 846 to not overwrite the skip status.
- Updated print statements for the reason of tests getting skipped in various PCIe tests.
=> Bug fixes and formatting changes in PCIe tests.

baremetal_app/SbsaAvsMain.c
- Updated val_execute_pcie_tests API call to align with UEFI.
- Modified PCIe tests entry level in baremetal.
=> Aligning baremetal PCIe infra with UEFI

test_pool/pe/operating_system/test_c016.c
The MPAM test was checking PPTT flags even if MPAM is not supported. This caused the test to fail when it should be skipped. This change follows the test description in the SBSA Test Scenario document, Test 16 Page 10, where it check MPAM support first. https://github.com/ARM-software/sbsa-acs/blob/master/docs/ Arm_SBSA_Architecture_Compliance_Test_Scenario.pdf
=> pe/os/test_co16.c: Skip MPAM test if it isn't supported

val/src/avs_timer.c
- UEFI was seen using virtual timer to generate
monotonic timer ticks using the EL1 virtual timer in QEMU,
disabling it so that it doesn't interfere with
interrupt related tests.
=> Disable EL1 VIRT timer before running tests

val/src/avs_pe_infra.c
#348 : Added cache-invalidate operation
- Secondary cores directly read g_pe_info_table->pe_info ->mpidr/pe_num without cache-invalidate operation in val_pe_get_index_mpid().
=> Added cache-invalidate operation

platform/pal_baremetal/src/pal_ras.c
- Incremented the curr_node pointer to the next one so that the table does not overwrite the next node's data in system with multiple RAS nodes.
=> Bug fixes for pal_ras_create_info_table in BM

platform/pal_uefi/include/pal_uefi.h, platform/pal_uefi/src/pal_pcie.c, platform/pal_uefi/src/pal_pcie_enumeration.c
- Each HandleBuffer allocated by LocateHandleBuffer() needs a FreePool(HandleBuffer) to free the memory avoid any memory leaks
- Freed HandleBuffer in the API's that allocated the same using LocateHandleBuffer()
=> Each HandleBuffer needs FreePool

val/src/avs_pcie.c
- Whenever the test encounters an EP without an assigned RP, the system will report error. Simultaneously, the test will continue its execution without interruption, progressing with the evaluation of other tests as usual. By implementing this change, we can maintain the overall efficiency of our testing operations while proactively addressing any incomplete or missing information.
=> ACS continues to test PCIe with Hierarchy error

platform/pal_baremetal/FVP/RDN2/include/platform_override_fvp.h, platform/pal_baremetal/FVP/RDN2/include/platform_override_struct.h, platform/pal_baremetal/FVP/RDN2/src/platform_cfg_fvp.c, platform/pal_baremetal/FVP/src/pal_bm_iovirt.c, platform/pal_baremetal/src/pal_iovirt.c
- Included a new structure for coresight components
- pal_get_device_path API is implemented for baremetal
- Named components device name parameter moved to platform_override_fvp.h
- Minor bug fixes for PMCG nodes parsing code.
=> Added support to Coresight components in Baremetal

val/src/avs_pcie.c
- If there are no tests to be run in the module, skip the module before performing any other module related checks.
=> Rearranging skip logic before other checks

val/include/sbsa_avs_exerciser.h
- Mismatch between function prototype and definition causing build failure with GCC 13.1.1
- Fixed the function prototype for val_get_exerciser_err_info
=> Fix for mismatch in function prototype

test_pool/exerciser/operating_system/test_e003.c, val/include/sbsa_avs_iovirt.h, val/src/avs_iovirt.c
- At Transaction Layer Packet (TLP) level, the ATS packets are handled differently compared to a normal TLP packet.
- If a Root Complex does not support ATS and receives an ATS packet, it may process it incorrectly, leading to potential errors.
- The ACPI table description of "ats_attr" provides the ats information of the RC.
- To ensure a reliable test, it is advisable to retrieve the "ats_attr" information from the "IOVIRT_RC_INFO_BLOCK" and proceed or skip the test accordingly.
=> ATS support check for Root Complex

val/src/avs_pcie.c
- Better messaging by adding prints of the capability id that is not found for register check tests
=> Fix for issue #373

test_pool/pcie/operating_system/test_p035.c
- The BAR values need not be all 0's after FLR is completed. It can be any value.
- Fix as part of https://github.com/ARM-software/bsa-acs/issues/192
=> BAR Values should not be 0 after FLR

val/src/avs_exerciser.c, val/src/avs_gic.c, val/src/avs_memory.c, val/src/avs_mpam.c, val/src/avs_nist.c, val/src/avs_pcie.c, val/src/avs_pe.c, val/src/avs_peripherals.c, val/src/avs_pmu.c, val/src/avs_ras.c, val/src/avs_smmu.c, val/src/avs_status.c, val/src/avs_test_infra.c, val/src/avs_timer.c, val/src/avs_wakeup.c, val/src/avs_wd.c
- Resolves: #381
- No console prints for tests not mentioned in -t option.
- Total test count aligns with the tests that are actually being run with user override options.
=> Enhancements to -t option

test_pool/pe/operating_system/test_c016.c
-Added val_print for MSC count error in test
Fixes #384
=> Adding more Verbosity to PE Test 16

test_pool/pcie/operating_system/test_p035.c
- Skip the FLR check for mass storage devices as they will be reset and logs cannot be stored
=> FLR should not be run for Mass storage devices

val/src/avs_pcie.c
- The number of ECAM regions is printed in hex. Changed it to %ld to maintain consistency in print messages
=> Fix for print the number of ecam

platform/pal_uefi/include/pal_mpam.h, test_pool/pe/operating_system/test_c016.c
MPAM Resource Select change added
- MPAM Table Structure changed according to MPAM v2.0 ACPI Table
- Now the test is updated to change RIS_SEL based on the rsrc_index
=> MPAM Resource Select change added

test_pool/pcie/operating_system/test_p050.c, test_pool/pcie/operating_system/test_p056.c
- Certain API's are platform dependent
- Adding the info as print msg for better understanding to customers
=> Fix for issue https://github.com/ARM-software/bsa-acs/issues/208

test_pool/pe/operating_system/test_c036.c, val/include/val_interface.h, val/src/avs_pe_infra.c
- It is recommended that PEs implement the WFE fine-tuning delay feature, Changing from fail to skip.
- Added VAL API to get the primery PE index which helps to print only when test is running on primary PE
- Added a print to display value of ID_AA64MMFR0_EL1.TWED only when test is running on primary PE.
=> L7_PE_09 is recommendation test

test_pool/pe/operating_system/test_c017.c
- Updated the condition to check ID_AA64DFR0_EL1.PMSVer minimum FEAT_SVE is implemented
- Added a print to display values of ID_AA64PFR0_EL1.SVE and ID_AA64DFR0_EL1.PMSVer only when test is running on primary PE.
=> check min FEAT_SPEv1p1 implemented

platform/pal_baremetal/common/include/pal_common_support.h, platform/pal_uefi/include/pal_uefi.h, test_pool/pcie/operating_system/test_p009.c, val/include/pal_interface.h
Fixes irq_to_hwirq() API should have a return type of uint64
=> Fixes irq_to_hwirq() API should have a return type of uint64

baremetal_app/SbsaAvsMain.c, platform/pal_baremetal/RDN2/include/platform_override_fvp.h, platform/pal_uefi/src/pal_mpam.c, test_pool/pe/operating_system/test_c016.c, uefi_app/SbsaAvsMain.c, val/include/sbsa_avs_cfg.h, val/include/val_interface.h, val/src/avs_mpam.c
- Added support to parse and check for cpor support by memory side last level cache.
- Level 1 mem-side cache present near to memory is considered as mem-side LLC.
Fixes: #388
=> PE test 16, check for CPOR support for LLC presented as mem-side

test_pool/pe/operating_system/test_c010.c, test_pool/pe/operating_system/test_c014.c, test_pool/pe/operating_system/test_c030.c, test_pool/pe/operating_system/test_c033.c, val/include/sbsa_avs_pe.h, val/src/AArch64/PeRegSysSupport.S, val/src/avs_pe.c
- The rule S_l7PE_03 is changed to check for AMU support  (668)
- The rule S_L5PE_07 is changed to check for FEAT_NV   (659)
- The S_L5PE_02 is changed to check for both generic and address auth (581, 582)
- The rule S_L7PE_06 has added to check for one of QARMA3 and QARMA5 (581, 582)
=> Sbsa Errata Mantis - 668, 659, 581 and 582

platform/pal_baremetal/RDN2/src/pal_bm_exerciser.c, platform/pal_uefi/src/pal_exerciser.c, test_pool/exerciser/operating_system/test_e002.c, test_pool/exerciser/operating_system/test_e003.c
- Exerciser does not have a way to identify the status of DMA transaction as they are posted requests.
- Removed DMA status dependency on exerciser APIs.
- Mem compare of input and output buffers verifies the status of DMA transactions.
=> Removing DMA status dependency on exerciser

test_pool/pcie/operating_system/test_p050.c
- This rule is not requried to run for iEP_RP iEP_EP, as the rule IE_INT_1 and IE_INT_2 implies that iEP devices must generate only MSI or MSI-X interrupts and must not have any wire-based interrupts
=> Remove iEPs from test 850

baremetal_app/SbsaAcsMain.c, linux_app/sbsa-acs-app/sbsa_app_main.c, uefi_app/SbsaAvsMain.c
- Added new argument "-only" to only run tests belonging to a specific level of compliance
- Changes in app files for prints when this option is passed
=> Added new argument "-only"

tools/scripts/acsbuild.sh, uefi_app/SbsaAvs.inf, uefi_app/SbsaAvsNist.inf
1.  Resolves #446 
2.  -I compiler option now uses BSA_PATH instead of WORKSPACE.
3.  BSA_PATH to be set by acsbuild.sh script.
=> Removing WORKSPACE dependency from .inf files

test_pool/pe/operating_system/test_c016.c
- seventh byte of MPAM descriptor 1 captures level for mem side cache.
Fixes : #450
=> PE test 16: fix parsing of mem-side cache level

test_pool/pcie/operating_system/test_p035.c
- Skipped the FLR check for ethernet devices as FLR might cause data corruption and disrupt the init of the device
=> Skipping Ethernet device for FLR test

README.md
The order of the arguments passed to `sbsa_setups.sh` is wrong in the README.md file. This commit fixes it.
=> README: Fix argument order of sbsa_setup.sh

test_pool/pe/operating_system/test_c023.c
The PE Test-23 is updated to check either FEAT_CSV2 or FEAT_CSV2_3 is present along with FEAT_CSV3 support.
Fixes #461
=> Sbsa Mantis 710

README.md, baremetal_app/SbsaAcsMain.c, uefi_app/SbsaAvs.h, uefi_app/SbsaAvsMain.c
- allocated memory for PCC info table and calling
val_pcc_create_info_table.
- allocated memory for pcc info table.
Fixes: #454 
Deps: https://github.com/ARM-software/bsa-acs/pull/344
=> Add support for PCCT based MSC

test_pool/pcie/operating_system/test_p064.c, test_pool/smmu/operating_system/test_i017.c
- The RCs and SMMUs must support ATS and must get the data from firmware.
- Errata 594
=> Errata Update - RC & SMMU ATS checks

test_pool/mpam/operating_system/test_mpam006.c
- Resolves #483
- Check for max_pmg >= 2 required. Else, could lead to Out-of-range PMG behaviour.
=> max_pmg check for MPAM test 006

test_pool/pe/operating_system/test_c021.c
Updates to PE test 21 
- Test checks for all values >= 0b0010
=> Fixes #488 : PE Test 21

test_pool/mpam/operating_system/test_mpam003.c
- Resolves #482
- Giving 30% room for MBWU monitor count when it encounters buffer memcpy
=> Relaxing MBWU monitor count check

test_pool/pcie/operating_system/test_p024_data.h
- RCiEP and i-EP acceptable latency requirement relaxation
- Only for RP's the latency to be hardwired to 0 as defined in the PCIe Spec
- Errata 747
=> Latency requirement relaxation

test_pool/exerciser/operating_system/test_e008.c, test_pool/pcie/operating_system/test_p056.c, test_pool/pcie/operating_system/test_p057.c
- val_pcie_p2p_support API either return non_implemented or 0. having it twice is redundant, hence removed it in tests
- In addition to the devices, the PCIe hierarchy also need to support P2P. hence added P2P check for PCIe hierarchy as well
=> Fix for https://github.com/ARM-software/bsa-acs/issues/352

test_pool/smmu/operating_system/test_i001.c
Fix for #513 - Smmu Sbsa Test will fail for no smmu compatibility
-The no smmu check before running the smmu tests is removed.
- If the smmu compatibility fails then other tests will not run
=> Smmu Sbsa Test will fail for no smmu compatibility

test_pool/pcie/operating_system/test_p003.c
- The UEFI PAL implementation to get the ECAM address was getting only from the segment 0 and not w.r.t the respective segments.
- Modified the PAL to check for the Segment and bus no of the BDF
=> Fixes #521 Exerciser on multi-segments

test_pool/pmu/operating_system/test_pmu004.c, test_pool/pmu/operating_system/test_pmu005.c, test_pool/pmu/operating_system/test_pmu007.c, test_pool/pmu/operating_system/test_pmu008.c, test_pool/pmu/operating_system/test_pmu009.c
Use the BSA API to check if PMU node following coresight regsister layout and skip test accordingly.
=> PMU test changes: Skip the test if PMU node not following CS pmu register layout.

test_pool/pe/operating_system/test_c017.c
- Fixes #541 
- Check for FEAT_SPEv1p1 was performed without checking if SPE is implemented.
- The B_PE_17 rule mentions that FEAT_SPEv1p1 must be supported only if SVE and SPE are implemented
- Therefore, if SPE not implemented, skip the test.
- Changes in copyright
=> Check FEAT_SPEv1p1 only if SPE and SVE implemented

test_pool/pe/operating_system/test_c040.c
Fixes #551 
-FEAT_LS64_V must be implemented if FEAT_LS64_ACCDATA is supported
=> Adding additional support for FEAT_LS64_ACCDATA

test_pool/smmu/operating_system/test_i014.c
- Accessing a unmapped region for pmcg node in test 314 results in exception.
- Before accessing the address is mapped.
=> if the PMCG node are not memory mapped, map them

baremetal_app/SbsaAcsMain.c, uefi_app/SbsaAvsMain.c
-  The messages indicating the total tests run, passed, and failed, along with the final SBSA test completion message, are printed for verbose 4 and 5.
=> Enhancment of Print for ERR in SBSA test summary

test_pool/pmu/operating_system/test_pmu004.c, test_pool/pmu/operating_system/test_pmu005.c, test_pool/pmu/operating_system/test_pmu007.c, test_pool/pmu/operating_system/test_pmu008.c, test_pool/pmu/operating_system/test_pmu009.c
Fixes #548 
-The PMU test relies on CoreSight PMU register layout 
-In case if PMU are not CoreSight PMU, manual verification of A.4 PMU rules are required.
- Add the prints with above details for all the PMU tests.
=> Update sys PMU test skipped reason in case of no CoreSight PMU

test_pool/ete/operating_system/test_ete004.c
Fixes #559, #558 
- The Bit Selection For FEAT_TRBE_EXT is corrected.
- It is corrected from reading 6:49 to 56:59 which represents ID_AA64DFR0_EL1.ExtTrcBuff
- As Per Arm Arch and BSA/SBSA spec there is no need for ID_AA64DFR0_EL1.ExtTrcBuff
- The test will Skip if there is no FEAT_TRBE_EXT support instead of Fail.
.
=> Test 1404: Check Trace Same Timestamp Source

test_pool/pe/operating_system/test_c028.c
Fixes #565 
Added Support for FEAT_FGT2
- Test now checks for both FEAT_FGT & FEAT_FGT2 as valid values.
=> Added Support for FEAT_FGT2
