ARM-software/sbsa-acs

- val/src/avs_pe_infra.c
Signed-off-by: Sakar Arora <Sakar.Arora@arm.com>
> Bug fix for undefined function reference in kernel module

- platform/pal_uefi/src/pal_iovirt.c
Signed-off-by: Sakar Arora <Sakar.Arora@arm.com>
> iovirt: Bug in calculating ID mapping ranges fixed

- linux_app/sbsa-acs-app.bb
> SBSA/linux_app: update checksum for bitbake recipe

- linux_app/sbsa-acs-app.bb
> Update source checksum for release branch

- uefi_app/SbsaAvs.h
> Increase gic and pcie info table sizes

- platform/pal_uefi/include/pal_uefi.h
- platform/pal_uefi/src/pal_iovirt.c
- test_pool/pcie/test_p011.c
- val/include/pal_interface.h
- val/src/avs_iovirt.c
> iovirt/pcie: Fix bug in saving root complex attributes

- test_pool/io_virt/test_i001.c
- test_pool/io_virt/test_i002.c
- test_pool/io_virt/test_i003.c
- test_pool/io_virt/test_i004.c
- test_pool/io_virt/test_i005.c
- test_pool/io_virt/test_i006.c
- test_pool/power_wakeup/test_u001.c
- val/src/avs_gic.c
- val/src/avs_iovirt.c
- val/src/avs_smmu.c
- val/src/avs_wd.c
This is to enable a consistent view of tests across all platforms and to present a full view of tests being skipped.
> Removing the feature of bulk skipping of tests. 

- test_pool/gic/test_g002.c
- test_pool/gic/test_g003.c
- test_pool/gic/test_g004.c
- test_pool/pcie/test_p012.c
Made a logical change to the test #62 PCI test loop and the error conditions.
> Fix for test #62 and other minor changes.

- test_pool/pcie/test_p015.c
Signed-off-by: Mahesh Bireddy <mahesh.reddybireddy@arm.com>
> Test 65: Bug fix, skipping snoop bit check for type-1 and type-2 headers

- test_pool/pcie/test_p007.c
- val/include/pal_interface.h
- val/include/val_interface.h
- val/src/avs_pcie.c
- val/src/avs_peripherals.c
Signed-off-by: Mahesh Bireddy <mahesh.reddybireddy@arm.com>
> Bug fix test 57: Checks MSI/MSI-X support for all pcie devices

- test_pool/peripherals/test_d003.c
Signed-off-by: Rajat Goyal <Rajat.Goyal@arm.com>
> BugFix test #84 : Check Generic UART Interrupt

- README.md
The latest version of the SBSA documentation has moved. This commit
updates the URLs accordingly.
> Update README.md with newest SBSA URL

- platform/pal_uefi/SbsaPalLib.inf
- platform/pal_uefi/include/pal_exerciser.h
- platform/pal_uefi/src/pal_exerciser.c
- val/SbsaValLib.inf
- val/include/val_exerciser.h
- val/src/avs_exerciser.c
> Adds PCIe exerciser frame work

- platform/pal_uefi/SbsaPalLib.inf
- platform/pal_uefi/include/pal_uefi.h
- platform/pal_uefi/src/pal_gic.c
- test_pool/timer_wd/test_w002.c
- val/include/pal_interface.h
- val/include/val_interface.h
- val/src/avs_gic.c
- val/src/avs_wd.c
Updated WS0 interrupt test to use the feature.
Signed-off-by: Rajat Goyal <Rajat.Goyal@arm.com>
> watchdog: Add support for setting interrupt trigger type

- platform/pal_uefi/include/pal_uefi.h
- platform/pal_uefi/src/pal_iovirt.c
- val/include/pal_interface.h
> Increase IORT named component node length to 256 bytes

- platform/pal_uefi/include/pal_uefi.h
- platform/pal_uefi/src/pal_iovirt.c
- val/include/pal_interface.h
> IORT named component node length increased to 256 bytes

- README.md
- linux_app/sbsa-acs-app/include/sbsa_app.h
- uefi_app/SbsaAvs.h
> Updated version number to 2.2

- linux_app/sbsa-acs-app/include/sbsa_app.h
- platform/pal_uefi/src/pal_misc.c
- test_pool/pe/test_c008.c
- uefi_app/SbsaAvs.h
- val/include/sbsa_avs_pe.h
- val/src/AArch64/PeTestSupport.S
- val/src/avs_pcie.c
- val/src/avs_pe.c
> Update copyright headers

- val/src/avs_timer.c
> Corrects the Generic Timer Interrupt enable sequence

- README.md
- platform/pal_uefi/src/pal_peripherals.c
- Updated the specification link in README.md to reflect to
SBSA v6.0 version
- Bug fix to assign the address value before NULL check
> Bug fix and doc link updates

- test_pool/peripherals/test_m001.c
> Peripherals: Reverting the test logic for test_m001

- test_pool/exerciser/test_e015.c
- The best way is to read the configuration registers into an array and write back the same values. 
Because currently, the test is writing to read-only registers and also to control and status registers, which is not advisable
and these values depend from EP to EP.
- Removing unaligned access of Device memory
> Exerciser: Read the configuration registers into an array and write back

- platform/pal_uefi/include/pal_exerciser.h
- platform/pal_uefi/src/pal_exerciser.c
- platform/pal_uefi/src/pal_iovirt.c
- platform/pal_uefi/src/pal_pcie.c
- test_pool/exerciser/test_e003.c
- test_pool/exerciser/test_e005.c
- test_pool/exerciser/test_e007.c
- test_pool/exerciser/test_e008.c
- test_pool/exerciser/test_e011.c
- test_pool/exerciser/test_e012.c
- test_pool/exerciser/test_e013.c
- test_pool/exerciser/test_e014.c
- val/include/pal_interface.h
- val/include/sbsa_avs_pcie.h
- val/include/sbsa_avs_pcie_spec.h
- val/include/val_interface.h
- val/src/avs_iovirt.c
- val/src/avs_pcie.c
- val/src/avs_pgt.c
- The exerciser registers have been updated. Exerciser
PAL has been updated to reflect this.
- Obtaining correct SMMU base for the given RID
- Enabled ATS for exerciser
- Bug fixes
> Exerciser: Updated exerciser functionality

- README.md
> ACS v3.1 Updates

- val/include/val_interface.h
- val/src/avs_exerciser.c
- val/src/avs_gic.c
- val/src/avs_memory.c
- val/src/avs_nist.c
- val/src/avs_pcie.c
- val/src/avs_pe.c
- val/src/avs_peripherals.c
- val/src/avs_smmu.c
- val/src/avs_test_infra.c
- val/src/avs_timer.c
- val/src/avs_wakeup.c
- val/src/avs_wd.c
Each test group printed information at the end. It was
done in different ways. Now all do the same.
> introduce val_print_test_end() function

- test_pool/timer_wd/test_w003.c
- uefi_app/SbsaAvsMain.c
- WD revision 1 is recommended for level 5 and mandatory for level 6 as per SBSA 6.1 specifications.
> WD test 303 changes

- platform/pal_baremetal/include/pal_common_support.h
- val/include/sbsa_avs_pcie_spec.h
> PCIe: Fix offsets of PCIe Capability registers

- README.md
Updated PCIe and Exerciser test dependency for platform-specific APIs
Change-Id: I00a191a12f10999ca5518172f72f85db09308bbc
> Docs: Updated readme limitations with affected tests

- test_pool/pcie/test_p003.c
- Configuration space of each functions are accessed only for
the start and end offset
Co-authored-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
Co-authored-by: Sujana M <sujana.m@arm.com>
> PCIe: Modified 403 to check only the start and end cfg

- test_pool/pcie/test_p003.c
> PCIe: RP is not assumed to be on Dev 0 Func 0

- test_pool/power_wakeup/test_u001.c
- test_pool/timer_wd/test_t001.c
- val/include/val_interface.h
- val/src/avs_wd.c
> Fix for issue #229

- val/sys_arch_src/gic/its/sbsa_gic_its.c
> Memory alignment mismatch fix

- test_pool/timer_wd/test_w003.c
-Modified Test description and Debug prints
Signed-off-by: Shyamanth RH <shyamanth.rh@arm.com>
> Changes in Watchdog test 303

- test_pool/peripherals/test_d003.c
* UART status register bits can change based on UART activity irrespective of test write check which can lead to false failures
* Currently test is making sure that no exception during write to RO registers
> Removed read only check for UART status registers

- test_pool/pe/test_c004.c
- test_pool/pe/test_c036.c
- Fixes to update the check for Arch version
greater than v8.5
> PE test 4 & 36 enhancements for Arm v8.7

- uefi_app/SbsaAvs.inf
> enforce no optimization for test layer build

- tools/scripts/avsbuild.sh
Code changes to allow for aarch64 native build
> AArch64 native build support

- val/src/avs_pcie.c
Signed-off-by: Shyamanth RH <shyamanth.rh@arm.com>
> Fix to select single pcie test to run

- test_pool/smmu/operating_system/test_i015.c
- test title changed to convey check being done for SMMU.
Resolves: #334
> Rename SMMU test 315

- val/include/val_interface.h
- val/src/avs_exerciser.c
- val/src/avs_gic.c
- val/src/avs_memory.c
- val/src/avs_mpam.c
- val/src/avs_nist.c
- val/src/avs_pcie.c
- val/src/avs_pe.c
- val/src/avs_peripherals.c
- val/src/avs_pmu.c
- val/src/avs_ras.c
- val/src/avs_smmu.c
- val/src/avs_test_infra.c
- val/src/avs_timer.c
- val/src/avs_wakeup.c
- val/src/avs_wd.c
- Added new val API to print out module headers on output console.
- Replaced val_print with new API to print module headers.
> Infra changes aligning to module header prints

- baremetal_app/SbsaAvsMain.c
- uefi_app/SbsaAvsMain.c
- val/src/avs_exerciser.c
- val/src/avs_mpam.c
- val/src/avs_pcie.c
- val/src/avs_pmu.c
- val/src/avs_ras.c
- val/src/avs_smmu.c
- val/sys_arch_src/gic/its/sbsa_gic_its.c
- val/sys_arch_src/smmu_v3/smmu_v3.c
- Removed repetitive level checks in val/src
- Added entry level check for exerciser module.
- Formatting changes for hygeine console logs.
> Removed repetitive level checks

- uefi_app/SbsaAvs.h
Increased Info table size
- Added Table size for all the Info tables.
- Added a note for total size required for tables.
> Increased Info table size

- platform/pal_baremetal/FVP/RDN2/include/platform_override_fvp.h
- val/include/pal_interface.h
- val/sys_arch_src/smmu_v3/smmu_v3.c
- SID bits can now be modified to avoid memory allocation issues when all SID bits are not required
> Added support to modify the SID bits

- test_pool/pmu/operating_system/test_pmu004.c
- test_pool/pmu/operating_system/test_pmu005.c
- test_pool/ras/operating_system/test_ras009.c
PMU, RAS test updates 
- PMU : Removing the un-used test_skip variable
RAS : Comments and debug prints added
> PMU, RAS test updates

- platform/pal_baremetal/src/pal_ras.c
- platform/pal_uefi/src/pal_ras.c
- test_pool/exerciser/operating_system/test_e002.c
- test_pool/exerciser/operating_system/test_e003.c
- test_pool/pcie/operating_system/test_p057.c
- test_pool/pe/operating_system/test_c016.c
- val/src/avs_pcie.c
- val/sys_arch_src/smmu_v3/smmu_reg.h
- Formatting changes for better ACS readability.
- Copyright updates.
- Updated SBSA rule for PCIe test p057.
> Formatting and copyright changes

- test_pool/pcie/operating_system/test_p035.c
- Few devices might require more than 100ms to complete the FLR.
- Hence modified to below logic Check if FLR PCIe capability is set If so, initiate FLR and Wait 100 ms Read back the VID register from config space If value is 0xFF, delay for 1 ms, then read again Keep polling until a maximum timeout of 5 secs
- Fix as part of https://github.com/ARM-software/bsa-acs/issues/194
> FLR test should poll for device readiness

- .github/workflows/build-sbsa-uefi.yml
- README.md
- patches/edk2-sbsa.diff
- added actions YAML and required edk2 patch.
- added build-status badge for scheduled cron
> Enable SBSA UEFI build Github actions

- test_pool/exerciser/operating_system/test_e005.c
- test_pool/pcie/operating_system/test_p024.c
- test_pool/pcie/operating_system/test_p039.c
Test description formatting changes
> Test description formatting changes

- test_pool/exerciser/operating_system/test_e007.c
- Test failing when exerciser is connected to a switch.
- When Secondary Bus Reset (SBR) reset is performed, the switch loses its values of primary bus, secondary and subordinate buses, as a result when trying to access below connected EPs config space,the request is not been forwarded.
- Restore the config space of switches and all its devices after SBR.
> Fix for Exerciser test 907

- README.md
- Added ACS version mapping in README for v23.11_BootFramework release.
> README version mapping updates

- uefi_app/SbsaAvs.h
Expanding the size of IORT table to support 2400 nodes
> Expanding the size of the IORT info table

- test_pool/gic/operating_system/test_g002.c
- uefi_app/SbsaAvsMain.c
- val/include/sbsa_avs_cfg.h
- val/src/avs_timer.c
> Porting  -el1physkip in sbsa-acs

- README.md
* Latest toolchain path provided
* Formatting changes
> README updates : SBSA linux app and module build steps

- .github/workflows/sbsa-acs_build_check.yml
- .github/workflows/sbsa-acs_daily_build.yml
- README.md
Split of .yml files based on:
-check-in build
-daily build
> Enhancement to Github Actions

- uefi_app/SbsaAvs.h
- Increase in PCIe table size to accomodate for 40 RC
> Increase in PCIe table size

- test_pool/pe/operating_system/test_c010.c
> Update test_c010.c : Correct the failure result status

- docs/PCIe_Exerciser/README.md
- docs/arm_sbsa_testcase_checklist.rst
- arm_sbsa_testcase_checklist.rst file to be rendered correctly on Github
- README.md file pointing to the latest stack
> Change in .rst file and README.md file

- test_pool/pe/operating_system/test_c032.c
> Update test_c032.c : Add check for EBF16

- test_pool/exerciser/operating_system/test_e001.c
- Addition of Rule ID to Exerciser test
> Fix for #479: Addition of Rule ID

- test_pool/pe/operating_system/test_c033.c
> Test description reformat for test 33

- test_pool/pe/operating_system/test_c004.c
-Adding additional FEAT_LPA2 check if FEAT_LPA is implemented
-If FEAT_LPA2 is implemented then test will pass
> Errata 669: FEAT_LPA and FEAT_LPA2 Check

- .github/workflows/sbsa-acs_build_check.yml
- .github/workflows/sbsa-acs_daily_build.yml
- patches/edk2-sbsa.diff
> Changes to take the latest edk2

- baremetal_app/SbsaAcsMain.c
- Allocation of memory for at least 1 peripheral information
> Fixes and enhancements

- test_pool/exerciser/operating_system/test_e006.c
- test_pool/exerciser/operating_system/test_e007.c
- Changes to reflect the MSI changes
> Changes to exerciser test 906 and 907

- .github/workflows/sbsa-acs_build_check.yml
- .github/workflows/sbsa-acs_daily_build.yml
- Updated the CI files to take ubuntu-22.04 instead of ubuntu-latest as this picks up ubuntu-24.04 randomly
> Update to .yml files for CI

- test_pool/ras/operating_system/test_ras005.c
Fixes: #525 
- Added code to initialize eri_id and fhi_id to zero in for loop
> Test 1205 needs to initialize eri_id and fhi_id in for loop

- test_pool/pcie/operating_system/test_p035.c
- When an FLR is initiated, and before the FLR being completed, the device will respond with Return Retry status (RRS) if Function-specific initialization sequence is not yet completed.
- The test should check for this status as well before proceeding to configuring the registers after FLR is completed
> Fixes #526: FLR test

- test_pool/ras/operating_system/test_ras004.c
- test_pool/ras/operating_system/test_ras010.c
- test_pool/ras/operating_system/test_ras011.c
- test_pool/ras/operating_system/test_ras013.c
The DEBUG and TEST level prints are added for FAIL and SKIP Reasons
> Debug Prints for RAS Tests

- baremetal_app/SbsaAcsMain.c
- linux_app/sbsa-acs-app/include/sbsa_app.h
- linux_app/sbsa-acs-app/sbsa_app_main.c
- uefi_app/SbsaAvsMain.c
The print messages are updated to print FR as level instead of level 8
> Print Format change for level FR

- README.md
- baremetal_app/SbsaAcs.h
- linux_app/sbsa-acs-app/include/sbsa_app.h
- uefi_app/SbsaAvs.h
The SBSA Version 7.2.1 is changed to 7.2.2
> README and Version Change

- test_pool/pe/operating_system/test_c032.c
- uefi_app/SbsaAvs.h
- uefi_app/SbsaAvsMain.c
- Made changes in SbsaAvsMain.c and SbsaAvs.h to have VAL calls instead of EFI calls from uefi_app to ensure the VAL/PAL flow.
- Changes in copyright
- Removal of trailing spaces
> Usage of VAL calls instead of UEFI calls

- test_pool/pcie/operating_system/test_p009.c
Added debug to print MSI value in success case for debugging
> 809 test debug prints

- test_pool/pcie/operating_system/test_p061.c
Added prints to help in debugging of test
Made tbl_index, bdf variable global to avoid any corruption due to exeception
> Updates to 861 test

- uefi_app/SbsaAvs.inf
- uefi_app/SbsaAvsNist.inf
- The Duplicate GUID in all files is replaced with Unique GUID
> Replace Duplicate GUID
